sudo: required
services: 
  - docker

before_install:
  - docker build -t abhishek-kumar-code/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run abhishek-kumar-code/react-test npm test -- --coverage

after_success:
  - docker build -t akumardocker7/multi-client ./client
  - docker build -t akumardocker7/multi-nginx ./nginx
  - docker build -t akumardocker7/multi-server ./server
  - docker build -t akumardocker7/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to Docker Hub
  - docker push akumardocker7/multi-client
  - docker push akumardocker7/multi-nginx
  - docker push akumardocker7/multi-server
  - docker push akumardocker7/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-309335768510"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
